[workspace]
resolver = "2"
members = [
    "simconnect-proto",
    "simconnect-derive",
    "simconnect",
    "simconnect-cli",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["TimTim"]
repository = "https://github.com/wegylexy/SimConnect"
keywords = ["simconnect", "msfs", "flight-simulator"]
categories = ["simulation", "network-programming"]
