// Batteries
/// Set the battery 1/2/3/4 switch to on or off. Parameters: \[0\]: bool.
pub const BATTERY1_SET: &str = "BATTERY1_SET";
/// Set the battery 1/2/3/4 switch to on or off. Parameters: \[0\]: bool.
pub const BATTERY2_SET: &str = "BATTERY2_SET";
/// Set the battery 1/2/3/4 switch to on or off. Parameters: \[0\]: bool.
pub const BATTERY3_SET: &str = "BATTERY3_SET";
/// Set the battery 1/2/3/4 switch to on or off. Parameters: \[0\]: bool.
pub const BATTERY4_SET: &str = "BATTERY4_SET";
/// Toggle the battery breaker state with a bus. Takes two indices, the bus and the battery
/// name (or index). See Event IDs As Key Events for more information. Parameters: \[0\]
/// Source bus.N name (or index) \[1\] battery.N name (or index).
pub const ELECTRICAL_BATTERY_BREAKER_TOGGLE: &str = "ELECTRICAL_BATTERY_BREAKER_TOGGLE";
/// Turns the named (or indexed) battery switch off. Parameters: \[0\]: battery.N name (or
/// index).
pub const MASTER_BATTERY_OFF: &str = "MASTER_BATTERY_OFF";
/// Turns the named (or indexed) battery switch on. Parameters: \[0\]: battery.N name (or
/// index).
pub const MASTER_BATTERY_ON: &str = "MASTER_BATTERY_ON";
/// Set the named (or indexed) battery switch state. Parameters: \[0\]: battery.N name (or
/// index) \[1\]: bool.
pub const MASTER_BATTERY_SET: &str = "MASTER_BATTERY_SET";
/// Toggle named (or indexed) battery switch state. Parameters: \[0\]: battery.N name (or
/// index).
pub const TOGGLE_MASTER_BATTERY: &str = "TOGGLE_MASTER_BATTERY";
/// Toggles named (or indexed) master battery and alternator switch Parameters: \[0\]:
/// battery.N name (or index).
pub const TOGGLE_MASTER_BATTERY_ALTERNATOR: &str = "TOGGLE_MASTER_BATTERY_ALTERNATOR";

// Breakers
/// Toggle the Fan breaker Parameters: \[0\]: circuit.N name (or index) \[1\]: Source bus.N
/// name (or index).
pub const BREAKER_AVNFAN_TOGGLE: &str = "BREAKER_AVNFAN_TOGGLE";
/// Toggle the autopilot breaker
pub const BREAKER_AUTOPILOT_TOGGLE: &str = "BREAKER_AUTOPILOT_TOGGLE";
/// Toggle the GPS breaker
pub const BREAKER_GPS_TOGGLE: &str = "BREAKER_GPS_TOGGLE";
/// Toggle the ADF breaker
pub const BREAKER_ADF_TOGGLE: &str = "BREAKER_ADF_TOGGLE";
/// Toggle the transponder breaker
pub const BREAKER_XPNDR_TOGGLE: &str = "BREAKER_XPNDR_TOGGLE";
/// Toggle the flaps breaker
pub const BREAKER_FLAP_TOGGLE: &str = "BREAKER_FLAP_TOGGLE";
/// Toggle the instruments breaker
pub const BREAKER_INST_TOGGLE: &str = "BREAKER_INST_TOGGLE";
/// Toggle the
pub const BREAKER_TURNCOORD_TOGGLE: &str = "BREAKER_TURNCOORD_TOGGLE";
/// Toggle the
pub const BREAKER_INSTLTS_TOGGLE: &str = "BREAKER_INSTLTS_TOGGLE";
/// Toggle the
pub const BREAKER_ALTFLD_TOGGLE: &str = "BREAKER_ALTFLD_TOGGLE";
/// Toggle the warning breaker
pub const BREAKER_WARN_TOGGLE: &str = "BREAKER_WARN_TOGGLE";
/// Toggle the Parameters: \[0\]: circuit.N name (or index).
pub const BREAKER_AVNBUS1_TOGGLE: &str = "BREAKER_AVNBUS1_TOGGLE";
/// Toggle the Parameters: \[0\]: circuit.N name (or index).
pub const BREAKER_AVNBUS2_TOGGLE: &str = "BREAKER_AVNBUS2_TOGGLE";
/// Toggle the NAV / COM 1 breaker Parameters: \[0\]: circuit.N name (or index).
pub const BREAKER_NAVCOM1_TOGGLE: &str = "BREAKER_NAVCOM1_TOGGLE";
/// Toggle the NAV / COM 2 breaker Parameters: \[0\]: circuit.N name (or index).
pub const BREAKER_NAVCOM2_TOGGLE: &str = "BREAKER_NAVCOM2_TOGGLE";
/// Toggle the NAV / COM 3 breaker Parameters: \[0\]: circuit.N name (or index).
pub const BREAKER_NAVCOM3_TOGGLE: &str = "BREAKER_NAVCOM3_TOGGLE";
/// Set the fan breaker Parameters: \[0\]: circuit.N name (or index) \[1\]: State, either
/// connected (1) or not (0). \[2\]: Source bus.N name (or index).
pub const BREAKER_AVNFAN_SET: &str = "BREAKER_AVNFAN_SET";
/// Set the autopilot breaker
pub const BREAKER_AUTOPILOT_SET: &str = "BREAKER_AUTOPILOT_SET";
/// Set the GPS breaker
pub const BREAKER_GPS_SET: &str = "BREAKER_GPS_SET";
/// Set the NAV/COM 1 breaker
pub const BREAKER_NAVCOM1_SET: &str = "BREAKER_NAVCOM1_SET";
/// Set the NAV/COM 2 breaker
pub const BREAKER_NAVCOM2_SET: &str = "BREAKER_NAVCOM2_SET";
/// Set the NAV/COM 3 breaker
pub const BREAKER_NAVCOM3_SET: &str = "BREAKER_NAVCOM3_SET";
/// Set the ADF breaker
pub const BREAKER_ADF_SET: &str = "BREAKER_ADF_SET";
/// Set the transponder breaker
pub const BREAKER_XPNDR_SET: &str = "BREAKER_XPNDR_SET";
/// Set the flaps breaker
pub const BREAKER_FLAP_SET: &str = "BREAKER_FLAP_SET";
/// Set the instrument breaker
pub const BREAKER_INST_SET: &str = "BREAKER_INST_SET";
/// Set the
pub const BREAKER_AVNBUS1_SET: &str = "BREAKER_AVNBUS1_SET";
/// Set the
pub const BREAKER_AVNBUS2_SET: &str = "BREAKER_AVNBUS2_SET";
/// Set the
pub const BREAKER_TURNCOORD_SET: &str = "BREAKER_TURNCOORD_SET";
/// Set the
pub const BREAKER_INSTLTS_SET: &str = "BREAKER_INSTLTS_SET";
/// Set the
pub const BREAKER_ALTFLD_SET: &str = "BREAKER_ALTFLD_SET";
/// Set the warning breaker
pub const BREAKER_WARN_SET: &str = "BREAKER_WARN_SET";

// Lights
/// Toggle all lights Parameters: \[0\]: circuit.N name (or index).
pub const ALL_LIGHTS_TOGGLE: &str = "ALL_LIGHTS_TOGGLE";
/// Turn beacon lights on Parameters: \[0\]: circuit.N name (or index).
pub const BEACON_LIGHTS_ON: &str = "BEACON_LIGHTS_ON";
/// Turn beacon lights off Parameters: \[0\]: circuit.N name (or index).
pub const BEACON_LIGHTS_OFF: &str = "BEACON_LIGHTS_OFF";
/// Set beacon lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const BEACON_LIGHTS_SET: &str = "BEACON_LIGHTS_SET";
/// Turn cabin lights off Parameters: \[0\]: circuit.N name (or index).
pub const CABIN_LIGHTS_OFF: &str = "CABIN_LIGHTS_OFF";
/// Turn cabin lights on Parameters: \[0\]: circuit.N name (or index).
pub const CABIN_LIGHTS_ON: &str = "CABIN_LIGHTS_ON";
/// Set cabin light circuit power setting. Takes two indices, the circuit and the power
/// setting (see Event IDs As Key Events for more information). Parameters: \[0\]: circuit.N
/// name (or index) \[1\]: power setting (%).
pub const CABIN_LIGHTS_POWER_SETTING_SET: &str = "CABIN_LIGHTS_POWER_SETTING_SET";
/// Set cabin lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const CABIN_LIGHTS_SET: &str = "CABIN_LIGHTS_SET";
/// Turn glareshield lights off Parameters: \[0\]: circuit.N name (or index).
pub const GLARESHIELD_LIGHTS_OFF: &str = "GLARESHIELD_LIGHTS_OFF";
/// Turn glareshield lights on Parameters: \[0\]: circuit.N name (or index).
pub const GLARESHIELD_LIGHTS_ON: &str = "GLARESHIELD_LIGHTS_ON";
/// Set glareshield light circuit power setting. Takes two indices, the circuit and the power
/// setting (see Event IDs As Key Events for more information). Parameters: \[0\]: circuit.N
/// name (or index) \[1\]: power setting (%).
pub const GLARESHIELD_LIGHTS_POWER_SETTING_SET: &str = "GLARESHIELD_LIGHTS_POWER_SETTING_SET";
/// Set glareshield lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0)
/// \[1\]: circuit.N name (or index).
pub const GLARESHIELD_LIGHTS_SET: &str = "GLARESHIELD_LIGHTS_SET";
/// Toggle glareshield lights Parameters: \[0\]: circuit.N name (or index).
pub const GLARESHIELD_LIGHTS_TOGGLE: &str = "GLARESHIELD_LIGHTS_TOGGLE";
/// Rotate landing light down Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHT_DOWN: &str = "LANDING_LIGHT_DOWN";
/// Return landing light to default position Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHT_HOME: &str = "LANDING_LIGHT_HOME";
/// Rotate landing light left Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHT_LEFT: &str = "LANDING_LIGHT_LEFT";
/// Rotate landing light right Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHT_RIGHT: &str = "LANDING_LIGHT_RIGHT";
/// Rotate landing light up Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHT_UP: &str = "LANDING_LIGHT_UP";
/// Turn landing lights on Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHTS_ON: &str = "LANDING_LIGHTS_ON";
/// Turn landing lights off Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHTS_OFF: &str = "LANDING_LIGHTS_OFF";
/// Set landing lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const LANDING_LIGHTS_SET: &str = "LANDING_LIGHTS_SET";
/// Toggle landing lights Parameters: \[0\]: circuit.N name (or index).
pub const LANDING_LIGHTS_TOGGLE: &str = "LANDING_LIGHTS_TOGGLE";
/// This can be used to set the colour of an ambient light. When providing a colour value,
/// this can be done using either a hexadecimal value or a decimal value, for example:
/// 0xFF994422 or 4288234530. For hexadecimal, it should be formatted as: 0xAABBGGRR.
/// 0xFF994422 1 (>K:2:LIGHT_AMBIENT_COLOR_SET) NOTE: This will set both the start and end
/// colour of the ambient light to the same colour. Parameters: \[0\]: Ambient light index
/// \[1\]: Colour value.
#[cfg(feature = "sunrise")]
pub const LIGHT_AMBIENT_COLOR_SET: &str = "LIGHT_AMBIENT_COLOR_SET";
/// (no description provided by the vendor docs)
pub const LIGHT_POTENTIOMETER_INC: &str = "LIGHT_POTENTIOMETER_INC";
/// (no description provided by the vendor docs)
pub const LIGHT_POTENTIOMETER_DEC: &str = "LIGHT_POTENTIOMETER_DEC";
/// (no description provided by the vendor docs) Parameters: \[0\]: circuit.N name (or index)
/// \[1\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_SET: &str = "LIGHT_POTENTIOMETER_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_1_SET: &str = "LIGHT_POTENTIOMETER_1_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_2_SET: &str = "LIGHT_POTENTIOMETER_2_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_3_SET: &str = "LIGHT_POTENTIOMETER_3_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_4_SET: &str = "LIGHT_POTENTIOMETER_4_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_5_SET: &str = "LIGHT_POTENTIOMETER_5_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_6_SET: &str = "LIGHT_POTENTIOMETER_6_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_7_SET: &str = "LIGHT_POTENTIOMETER_7_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_8_SET: &str = "LIGHT_POTENTIOMETER_8_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_9_SET: &str = "LIGHT_POTENTIOMETER_9_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_10_SET: &str = "LIGHT_POTENTIOMETER_10_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_11_SET: &str = "LIGHT_POTENTIOMETER_11_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_12_SET: &str = "LIGHT_POTENTIOMETER_12_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_13_SET: &str = "LIGHT_POTENTIOMETER_13_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_14_SET: &str = "LIGHT_POTENTIOMETER_14_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_15_SET: &str = "LIGHT_POTENTIOMETER_15_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_16_SET: &str = "LIGHT_POTENTIOMETER_16_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_17_SET: &str = "LIGHT_POTENTIOMETER_17_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_18_SET: &str = "LIGHT_POTENTIOMETER_18_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_19_SET: &str = "LIGHT_POTENTIOMETER_19_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_20_SET: &str = "LIGHT_POTENTIOMETER_20_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_21_SET: &str = "LIGHT_POTENTIOMETER_21_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_22_SET: &str = "LIGHT_POTENTIOMETER_22_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_23_SET: &str = "LIGHT_POTENTIOMETER_23_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_24_SET: &str = "LIGHT_POTENTIOMETER_24_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_25_SET: &str = "LIGHT_POTENTIOMETER_25_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_26_SET: &str = "LIGHT_POTENTIOMETER_26_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_27_SET: &str = "LIGHT_POTENTIOMETER_27_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_28_SET: &str = "LIGHT_POTENTIOMETER_28_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_29_SET: &str = "LIGHT_POTENTIOMETER_29_SET";
/// (no description provided by the vendor docs) Parameters: LIGHT_POTENTIOMETER_1_SET
/// LIGHT_POTENTIOMETER_2_SET LIGHT_POTENTIOMETER_3_SET LIGHT_POTENTIOMETER_4_SET
/// LIGHT_POTENTIOMETER_5_SET LIGHT_POTENTIOMETER_6_SET LIGHT_POTENTIOMETER_7_SET
/// LIGHT_POTENTIOMETER_8_SET LIGHT_POTENTIOMETER_9_SET LIGHT_POTENTIOMETER_10_SET
/// LIGHT_POTENTIOMETER_11_SET LIGHT_POTENTIOMETER_12_SET LIGHT_POTENTIOMETER_13_SET
/// LIGHT_POTENTIOMETER_14_SET LIGHT_POTENTIOMETER_15_SET LIGHT_POTENTIOMETER_16_SET
/// LIGHT_POTENTIOMETER_17_SET LIGHT_POTENTIOMETER_18_SET LIGHT_POTENTIOMETER_19_SET
/// LIGHT_POTENTIOMETER_20_SET LIGHT_POTENTIOMETER_21_SET LIGHT_POTENTIOMETER_22_SET
/// LIGHT_POTENTIOMETER_23_SET LIGHT_POTENTIOMETER_24_SET LIGHT_POTENTIOMETER_25_SET
/// LIGHT_POTENTIOMETER_26_SET LIGHT_POTENTIOMETER_27_SET LIGHT_POTENTIOMETER_28_SET
/// LIGHT_POTENTIOMETER_29_SET LIGHT_POTENTIOMETER_30_SET \[0\]: Potentiometer value.
pub const LIGHT_POTENTIOMETER_30_SET: &str = "LIGHT_POTENTIOMETER_30_SET";
/// Set logo lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const LOGO_LIGHTS_SET: &str = "LOGO_LIGHTS_SET";
/// Turn navigation lights on Parameters: \[0\]: circuit.N name (or index).
pub const NAV_LIGHTS_ON: &str = "NAV_LIGHTS_ON";
/// Turn navigation lights off Parameters: \[0\]: circuit.N name (or index).
pub const NAV_LIGHTS_OFF: &str = "NAV_LIGHTS_OFF";
/// Set navigation lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0)
/// \[1\]: circuit.N name (or index).
pub const NAV_LIGHTS_SET: &str = "NAV_LIGHTS_SET";
/// Turn panel lights on Parameters: \[0\]: circuit.N name (or index).
pub const PANEL_LIGHTS_ON: &str = "PANEL_LIGHTS_ON";
/// Turn panel lights off Parameters: \[0\]: circuit.N name (or index).
pub const PANEL_LIGHTS_OFF: &str = "PANEL_LIGHTS_OFF";
/// Set panel light circuit power setting. Takes two indices, the circuit and the power
/// setting (see Event IDs As Key Events for more information). Parameters: \[0\]: circuit.N
/// name (or index) \[1\]: power setting (%).
pub const PANEL_LIGHTS_POWER_SETTING_SET: &str = "PANEL_LIGHTS_POWER_SETTING_SET";
/// Set panel lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const PANEL_LIGHTS_SET: &str = "PANEL_LIGHTS_SET";
/// Toggle panel lights Parameters: \[0\]: circuit.N name (or index).
pub const PANEL_LIGHTS_TOGGLE: &str = "PANEL_LIGHTS_TOGGLE";
/// Turn pedestral lights off Parameters: \[0\]: circuit.N name (or index).
pub const PEDESTRAL_LIGHTS_OFF: &str = "PEDESTRAL_LIGHTS_OFF";
/// Turn pedestral lights on Parameters: \[0\]: circuit.N name (or index).
pub const PEDESTRAL_LIGHTS_ON: &str = "PEDESTRAL_LIGHTS_ON";
/// Set pedestal light circuit power setting. Takes two indices, the circuit and the power
/// setting (see Event IDs As Key Events for more information). Parameters: \[0\]: circuit.N
/// name (or index) \[1\]: power setting (%).
pub const PEDESTRAL_LIGHTS_POWER_SETTING_SET: &str = "PEDESTRAL_LIGHTS_POWER_SETTING_SET";
/// Set pedestral lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0)
/// \[1\]: light circuit name (or index).
pub const PEDESTRAL_LIGHTS_SET: &str = "PEDESTRAL_LIGHTS_SET";
/// Toggle pedestral lights Parameters: \[0\]: light circuit name (or index).
pub const PEDESTRAL_LIGHTS_TOGGLE: &str = "PEDESTRAL_LIGHTS_TOGGLE";
/// Set recognition lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0)
/// \[1\]: circuit.N name (or index).
pub const RECOGNITION_LIGHTS_SET: &str = "RECOGNITION_LIGHTS_SET";
/// Turn strobe lights on Parameters: \[0\]: circuit.N name (or index).
pub const STROBES_ON: &str = "STROBES_ON";
/// Turn strobe light off Parameters: \[0\]: circuit.N name (or index).
pub const STROBES_OFF: &str = "STROBES_OFF";
/// Set strobe lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const STROBES_SET: &str = "STROBES_SET";
/// Toggle strobe lights Parameters: \[0\]: circuit.N name (or index).
pub const STROBES_TOGGLE: &str = "STROBES_TOGGLE";
/// Turn taxi lights on Parameters: \[0\]: circuit.N name (or index).
pub const TAXI_LIGHTS_ON: &str = "TAXI_LIGHTS_ON";
/// Turn taxi light off Parameters: \[0\]: circuit.N name (or index).
pub const TAXI_LIGHTS_OFF: &str = "TAXI_LIGHTS_OFF";
/// Set taxi lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const TAXI_LIGHTS_SET: &str = "TAXI_LIGHTS_SET";
/// Toggle beacon lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_BEACON_LIGHTS: &str = "TOGGLE_BEACON_LIGHTS";
/// Toggle cockpit/cabin lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_CABIN_LIGHTS: &str = "TOGGLE_CABIN_LIGHTS";
/// Toggle logo lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_LOGO_LIGHTS: &str = "TOGGLE_LOGO_LIGHTS";
/// Toggle navigation lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_NAV_LIGHTS: &str = "TOGGLE_NAV_LIGHTS";
/// Toggle recognition lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_RECOGNITION_LIGHTS: &str = "TOGGLE_RECOGNITION_LIGHTS";
/// Toggle taxi lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_TAXI_LIGHTS: &str = "TOGGLE_TAXI_LIGHTS";
/// Toggle wing lights Parameters: \[0\]: circuit.N name (or index).
pub const TOGGLE_WING_LIGHTS: &str = "TOGGLE_WING_LIGHTS";
/// Turn wing lights off Parameters: \[0\]: circuit.N name (or index).
pub const WING_LIGHTS_OFF: &str = "WING_LIGHTS_OFF";
/// Turn wing light on Parameters: \[0\]: circuit.N name (or index).
pub const WING_LIGHTS_ON: &str = "WING_LIGHTS_ON";
/// Set wing lights on/off (1,0) Parameters: \[0\]: state, either on (1) or off (0) \[1\]:
/// circuit.N name (or index).
pub const WING_LIGHTS_SET: &str = "WING_LIGHTS_SET";

// Miscellaneous
/// Toggle the breaker state between buses. Takes two names (or indices), the source bus and
/// the target bus. See Event IDs As Key Events for more information. Parameters: \[0\]:
/// Source bus.N name (or index) \[1\]: Target bus.N name (or index).
pub const ELECTRICAL_BUS_BREAKER_TOGGLE: &str = "ELECTRICAL_BUS_BREAKER_TOGGLE";
/// Toggle alternator connection state with a bus. Takes two names (or indices), the bus and
/// the alternator. See Event IDs As Key Events for more information. Parameters: \[0\]:
/// Source bus.N name (or index) \[1\]: Alternator index.
pub const ELECTRICAL_BUS_TO_ALTERNATOR_CONNECTION_TOGGLE: &str =
    "ELECTRICAL_BUS_TO_ALTERNATOR_CONNECTION_TOGGLE";
/// Toggle battery connection state with a bus. Takes two names (or indices), the bus and the
/// battery. See Event IDs As Key Events for more information. Parameters: \[0\]: Source bus.N
/// name (or index) \[1\]: battery index.
pub const ELECTRICAL_BUS_TO_BATTERY_CONNECTION_TOGGLE: &str =
    "ELECTRICAL_BUS_TO_BATTERY_CONNECTION_TOGGLE";
/// Toggle bus connection state with a bus. Takes two names (or indices), the initial bus and
/// the second bus. See Event IDs As Key Events for more information. Parameters: \[0\]:
/// Source bus.N name (or index) \[1\]: Target bus.N name (or index).
pub const ELECTRICAL_BUS_TO_BUS_CONNECTION_TOGGLE: &str = "ELECTRICAL_BUS_TO_BUS_CONNECTION_TOGGLE";
/// Toggle circuit connection state with a bus. Takes two names (or indices), the bus and the
/// circuit. See Event IDs As Key Events for more information. Parameters: \[0\]: Source bus.N
/// name (or index) \[1\]: circuit.N name (or index).
pub const ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE: &str =
    "ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE";
/// Toggle external power connection state with a bus. Takes two names (or indices), the bus
/// and the external power source. See Event IDs As Key Events for more information.
/// Parameters: \[0\]: Source bus.N name (or index) \[1\]: externalpower.N name (or index).
pub const ELECTRICAL_BUS_TO_EXTERNAL_POWER_CONNECTION_TOGGLE: &str =
    "ELECTRICAL_BUS_TO_EXTERNAL_POWER_CONNECTION_TOGGLE";
/// Toggle the circuit breaker state with a bus. Takes two names (or indices), the bus and the
/// circuit index. See Event IDs As Key Events for more information. Parameters: \[0\] Source
/// bus.N name (or index) \[1\] Target circuit.N name (or index).
pub const ELECTRICAL_CIRCUIT_BREAKER_TOGGLE: &str = "ELECTRICAL_CIRCUIT_BREAKER_TOGGLE";
/// Set circuit power setting. Takes two names (or indices), the circuit and the power
/// setting. See Event IDs As Key Events for more information. Parameters: \[0\]: circuit.N
/// name (or index) \[1\]: circuit power setting (%).
pub const ELECTRICAL_CIRCUIT_POWER_SETTING_SET: &str = "ELECTRICAL_CIRCUIT_POWER_SETTING_SET";
/// Toggle the named (or indexed) circuit switch state. See Event IDs As Key Events for more
/// information. Parameters: \[0\]: circuit.N name (or index).
pub const ELECTRICAL_CIRCUIT_TOGGLE: &str = "ELECTRICAL_CIRCUIT_TOGGLE";
/// Execute a named (or indexed) procedure with bInverse as an optional argument IMPORTANT!
/// This event ID is only valid for V1.00 electrical systems. See here for more details:
/// LEGACY: systems.cfg - \[ELECTRICAL\] Parameters: \[0\]: procedure index \[1\]: bInverse
/// (optional).
pub const ELECTRICAL_EXECUTE_PROCEDURE: &str = "ELECTRICAL_EXECUTE_PROCEDURE";
/// Toggle the named (or indexed) external power breaker state with a bus. Takes two indices,
/// the bus and the external power index. See Event IDs As Key Events for more information.
/// Parameters: \[0\] Source bus.N name (or index) \[1\] externalpower.N name (or index).
pub const ELECTRICAL_EXTERNAL_POWER_BREAKER_TOGGLE: &str =
    "ELECTRICAL_EXTERNAL_POWER_BREAKER_TOGGLE";
/// (no description provided by the vendor docs)
#[cfg(feature = "sunrise")]
pub const ELECTRICAL_LINE_BREAKER_SET: &str = "ELECTRICAL_LINE_BREAKER_SET";
/// (no description provided by the vendor docs)
#[cfg(feature = "sunrise")]
pub const ELECTRICAL_LINE_BREAKER_TOGGLE: &str = "ELECTRICAL_LINE_BREAKER_TOGGLE";
/// (no description provided by the vendor docs)
#[cfg(feature = "sunrise")]
pub const ELECTRICAL_LINE_CONNECTION_SET: &str = "ELECTRICAL_LINE_CONNECTION_SET";
/// (no description provided by the vendor docs)
#[cfg(feature = "sunrise")]
pub const ELECTRICAL_LINE_CONNECTION_TOGGLE: &str = "ELECTRICAL_LINE_CONNECTION_TOGGLE";
/// Set the external power switch state. Parameters: \[0\]: externalpower.N name (or index)
/// \[1\]: The state on/off (1, 0).
pub const SET_EXTERNAL_POWER: &str = "SET_EXTERNAL_POWER";
/// Toggle external power switch state. Parameters: \[0\]: externalpower.N name (or index).
pub const TOGGLE_EXTERNAL_POWER: &str = "TOGGLE_EXTERNAL_POWER";
/// Toggles backup electric vacuum pump
pub const TOGGLE_ELECTRIC_VACUUM_PUMP: &str = "TOGGLE_ELECTRIC_VACUUM_PUMP";

// Alternator
/// Turns the indexed alternator off. The alternator index is the N index of the alternator.N
/// definition. Parameters: \[0\]: alternator.N Index.
pub const ALTERNATOR_OFF: &str = "ALTERNATOR_OFF";
/// Turns the indexed alternator on. The alternator index is the N index of the alternator.N
/// definition. Parameters: \[0\]: alternator.N Index.
pub const ALTERNATOR_ON: &str = "ALTERNATOR_ON";
/// Sets the indexed alternator. The alternator index is the N index of the alternator.N
/// definition. Parameters: \[0\]: The state on/off (bool) \[1\]: alternator.N Index.
pub const ALTERNATOR_SET: &str = "ALTERNATOR_SET";
/// Toggle the alternator breaker state with a bus. Takes two indices, the bus and the
/// alternator index (see Event IDs As Key Events for more information.). The bus index is the
/// N index of the bus.N definition, and the alternator index is the N index of the
/// alternator.N definition. Parameters: \[0\] Source bus.N Index \[1\] alternator.N Index.
pub const ELECTRICAL_ALTERNATOR_BREAKER_TOGGLE: &str = "ELECTRICAL_ALTERNATOR_BREAKER_TOGGLE";
/// Toggles alternator/generator 1/2/3/4 switch.
pub const TOGGLE_ALTERNATOR1: &str = "TOGGLE_ALTERNATOR1";
/// Toggles alternator/generator 1/2/3/4 switch.
pub const TOGGLE_ALTERNATOR2: &str = "TOGGLE_ALTERNATOR2";
/// Toggles alternator/generator 1/2/3/4 switch.
pub const TOGGLE_ALTERNATOR3: &str = "TOGGLE_ALTERNATOR3";
/// Toggles alternator/generator 1/2/3/4 switch.
pub const TOGGLE_ALTERNATOR4: &str = "TOGGLE_ALTERNATOR4";
/// Toggles main alternator/generator switch. The alternator index is the N index of the
/// alternator.N definition. Parameters: \[0\]: alternator.N Index.
pub const TOGGLE_MASTER_ALTERNATOR: &str = "TOGGLE_MASTER_ALTERNATOR";

// APU
/// Sets if the APU is the source of the bleed air system (true) or not (false). Parameters:
/// \[0\]: Generator name (or index) \[1\]: Bool.
pub const APU_BLEED_AIR_SOURCE_SET: &str = "APU_BLEED_AIR_SOURCE_SET";
/// Toggle if the APU is the source of the bleed air system or not. Parameters: \[0\]:
/// Generator name (or index).
pub const APU_BLEED_AIR_SOURCE_TOGGLE: &str = "APU_BLEED_AIR_SOURCE_TOGGLE";
/// Extinguish fire on APU using the indexed fire extinguisher. Parameters: \[0\]: fire
/// extinguisher index.
pub const APU_EXTINGUISH_FIRE: &str = "APU_EXTINGUISH_FIRE";
/// Turn the auxiliary generator on or off.
pub const APU_GENERATOR_SWITCH_TOGGLE: &str = "APU_GENERATOR_SWITCH_TOGGLE";
/// Set the auxiliary generator switch (0,1). Parameters: \[0\]: New switch value (0, or 1)
/// \[1\]: index of the APU switch.
pub const APU_GENERATOR_SWITCH_SET: &str = "APU_GENERATOR_SWITCH_SET";
/// Turn the APU off.
pub const APU_OFF_SWITCH: &str = "APU_OFF_SWITCH";
/// Start up the auxiliary power unit (APU).
pub const APU_STARTER: &str = "APU_STARTER";
