//! Known SimConnect *key event* names, organized by the MSFS2024 SDK docs'
//! own `Key_Events` sub-pages. These are plain strings passed to
//! `send::map_client_event_to_sim_event`/`transmit_client_event`, exactly
//! like the COM radio events in the parent module -- no new wire opcode or
//! struct.
//!
//! Generated by cross-referencing the MSFS2020 SDK docs
//! (`docs.flightsimulator.com/html/Programming_Tools/Event_IDs/`) against
//! the MSFS2024 SDK docs (`.../msfs2024/html/6_Programming_APIs/Key_Events/`)
//! straight from each page's HTML tables (not a paraphrased/summarized
//! fetch -- an earlier pass that used a summarizing fetch tool silently
//! mangled a large fraction of these names, e.g. inventing a `KEY_` prefix
//! that belongs to a *different* column on the 2024 docs page (the
//! keybinding name, not the SimConnect event string) and dropping/renaming
//! others; don't reintroduce that by hand-summarizing a fetched page again):
//! - present in both doc versions => ungated (FSX-era or MSFS2020-era name).
//! - present only in the 2024 docs => `#[cfg(feature = "sunrise")]`.
//! - `general_systems`/`balloon` have no MSFS2020-era doc page at all, so
//!   every constant in those two modules is `sunrise`-gated.
//! - explicitly marked "Deprecated"/"legacy" on the vendor page =>
//!   `#[deprecated]`.
//!
//! None of these have been independently confirmed against a live sim
//! capture the way `COM_RADIO_SET`/`system::SIM`/`system::PAUSE` have been --
//! treat the exact spelling as "per the vendor docs", not wire-verified by
//! this crate. A small number of names present in the 2020 docs no longer
//! appear anywhere in the 2024 docs (e.g. `STARTER_GEN`, `MAGNETO1_SET`) and
//! were dropped rather than guessed at.

pub mod aircraft_misc;
pub mod autopilot;
pub mod balloon;
pub mod electrical;
pub mod engine;
pub mod flight_control;
pub mod fuel_system;
pub mod general_systems;
pub mod helicopter;
pub mod instrumentation;
pub mod miscellaneous;
pub mod radio_navigation;
pub mod view_camera;
